# fly.toml app configuration file generated for reservatucancha on 2023-10-30T16:55:31-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reservatucancha"
primary_region = "bog"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
