# CREATE RESERVATION
POST http://localhost:3000/api/reservation
Content-Type: application/json

{
  "fr_date_reservation": "2023-10-30T09:00:00Z",
  "fr_status": "RESERVADO", 
  "fr_schedule": {
    "s_date_reserved": "2023-10-30T24:00:00.000Z",
    "s_start": "09:00:00",
    "s_end": "10:00:00"
  },
  "user_id": "652ff85a5e95f355a0630ce0",
  "sc_id": "65370b542b617a35521a4389",
  "sca_id": "65379b2f1a8f5bbe8785377c"
}

###Get reservation by id
GET http://localhost:3000/api/reservation/6542dfa7f7a366abe64af6f2