### GET DOC
GET http://localhost:3000/api-docs

### GET SPORTCENTER
GET http://localhost:3000/api/sportCenter

### GET SPORTCENTER BY ID
GET http://localhost:3000/api/sportCenter/652f180d58adadc2f9bc7a58

### POST SPORTCENTER
POST http://localhost:3000/api/sportCenter
Content-Type: application/json

// SE PODRIA PASAR EL NOMBRE DEL COUNTRY EN VEZ DE ID
{
  "name": "sportcenter 2",
  "description": "Description 2",
  "phone": 123456789,
  "email": "email2@example.com",
  "address": "address1",
  "lat": 1,
  "alt": 1,
  "open": true,
  "close": true,
  "active": true,
  "imgs": [
    "imagen1",
    "imagen2"
  ],
  "country_id": "652ff7625e95f355a0630cd9",
  "user_id": "652ff85a5e95f355a0630ce0"
}

### DELETE SPORTCENTER BY ID
DELETE  http://localhost:3000/api/sportCenter/652f180d58adadc2f9bc7a58

### UPDATE SPORTCENTER
PUT http://localhost:3000/api/sportCenter
Content-Type: application/json

{
  "name": "Otro sportcenter 1",
  "email": "otrocorreo1@example.com",
  "sportCenterId": "652f180d58adadc2f9bc7a58",
  "country_id": "65281e37b364c6c550d6647b"
}
