### GET DOC
GET http://localhost:3000/api-docs

### GET COUNTRY
GET http://localhost:3000/api/country

### POST COUNTRY
POST http://localhost:3000/api/country
Content-Type: application/json

// NO SE VA A CREAR, DIRECTO DE API.
// PARA PRUEBA:
{
  "name": "Colombia",
  "image": "imagen Colombia"
}

### GET TYPE
GET http://localhost:3000/api/types

### POST TYPE
POST http://localhost:3000/api/types
Content-Type: application/json

# {
#   "name": "Admin",
#   "description": "Administrador del sistema"
# }

# {
#   "name": "User",
#   "description": "Usuario que solicita una cancha"
# }

{
  "name": "Owner",
  "description": "Propietario de la cancha"
}

### GET USERS
GET http://localhost:3000/api/users

### GET USER BY ID
GET http://localhost:3000/api/users/65284aa094bf62b7a1ff788b

### POST USER
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Otro usuario 10",
  "lastname": "Otro apellido 10",
  "email": "correo10@example.com",
  "password": "111111",
  "city": "Buenos Aires",
  "address": "Av. Principal",
  "image": "imagen2",
  "country_id": "65281e37b364c6c550d6647b"
}

### DELETE USER BY ID
DELETE  http://localhost:3000/api/users/652ec81ea8b47f2baa08b2

### UPDATE USER
PUT http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Otro nombre 9",
  "email": "otrocorreo9@example.com",
  "userId": "652ec81ea8b47f2baa0862b2"
}

### LOGIN USER
POST http://localhost:3000/api/login
Content-Type: application/json

# {
#   "email": "mmmmm@example.com",
#   "password": "111111"
# }

{
  "email": "mmmmm@example.com",
  "password": "otracontraseña"
}

# {
#   "email": "otrocorreo@example.com",
#   "password": "otracontraseña"
# }